# Generated by Django 5.0.2 on 2024-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manhwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapter', models.IntegerField()),
                ('genre', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
